[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "owl-imdl"
version = "0.1.0"
description = "IMDL template engine"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]